name: ordinary
version: 1.0.2+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  camera: ^0.10.5+2
  get: ^4.6.6
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  tflite_flutter: ^0.10.4
  image: ^4.0.17
  path_provider: ^2.1.3
  image_picker: ^1.0.0
  exif: ^3.1.4
  firebase_core: ^2.30.0
  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_commons: ^0.6.1
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  intl: ^0.19.0
  csv: ^6.0.0
  path: ^1.9.0
  get_storage: ^2.1.1
  device_frame: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/models/
    - assets/images/
  uses-material-design: true
